import tkinter as tk
from PIL import ImageTk, Image
ventana = tk.Tk()
ventana.title("Mi primera ventana")
ventana.geometry("400x300")
ancho_pantalla = ventana.winfo_screenwidth()
alto_pantalla = ventana.winfo_screenheight()
x = (ancho_pantalla // 2) - (400 // 2)
y = (alto_pantalla // 2) - (300 // 2)
ventana.geometry(f"{400}x{300}+{x}+{y}")
resultado = tk.Label(ventana, text=f"Resultado = ")
resultado.place(x=160, y=140)
resultado.place_forget()
operando1 = tk.Label(ventana, text="Ingrese el primer operando:")
operando1.place( x = 30, y = 10)
entrada1 = tk.Entry(ventana)
entrada1.place( x = 30, y = 40)
operando2 = tk.Label(ventana, text="Ingrese el segundo operando:")
operando2.place( x = 220, y = 10)
entrada2 = tk.Entry(ventana)
entrada2.place( x = 220, y = 40)
def Suma():
    op1 = entrada1.get()
    op2 = entrada2.get()
    resultado.config(text=f"Resultado = {float(op1) + float(op2)}")
    resultado.place( x = 160, y = 140)
    boton_limpiar.place(x=180, y=200)
def Resta():
    op1 = entrada1.get()
    op2 = entrada2.get()
    resultado.config(text=f"Resultado = {float(op1) - float(op2)}")
    resultado.place(x=160, y=140)
    boton_limpiar.place(x=180, y=200)
   # entrada.delete(0, tk.END)
   # etiqueta.config(text="Escribe tu nombre:")
def Multiplicacion():
    op1 = entrada1.get()
    op2 = entrada2.get()
    resultado.config(text=f"Resultado = {float(op1) * float(op2)}")
    resultado.place(x=160, y=140)
    boton_limpiar.place(x=180, y=200)
def Division():
    op1 = entrada1.get()
    op2 = entrada2.get()
    resultado.config(text=f"Resultado = {float(op1) / float(op2)}")
    resultado.place(x=160, y=140)
    boton_limpiar.place(x=180, y=200)
def Limpiar():
    entrada1.delete(0, tk.END)
    entrada2.delete(0, tk.END)
    resultado.place_forget()
    boton_limpiar.place_forget()
boton_limpiar = tk.Button(ventana, text="Limpiar", command=Limpiar)
boton_limpiar.place( x = 180, y = 200)
boton_limpiar.place_forget()
imagen = Image.open("Al2.jpg")
imagen2 = Image.open("Al1.png")
imagen3 = Image.open("Chino.png")
imagen = imagen.resize((180, 80))
imagen2 = imagen2.resize((180, 80))
imagen3 = imagen3.resize((180, 80))
img = ImageTk.PhotoImage(imagen)
img2 = ImageTk.PhotoImage(imagen2)
img3 = ImageTk.PhotoImage(imagen3)
label_imagen = tk.Label(ventana, image = img)
label_imagen.place( x = 0 , y = 170)
label_imagen2 = tk.Label(ventana, image = img2)
label_imagen2.place( x = 0, y = 170)
label_imagen3 = tk.Label(ventana, image = img3)
label_imagen3.place( x = 0, y = 170)
suma = tk.Button(ventana, text="+", command=Suma)
suma.place( x = 30, y = 90)
resta = tk.Button(ventana, text="-", command=Resta)
resta.place( x = 140, y = 90)
multiplicacion = tk.Button(ventana, text="X", command=Multiplicacion)
multiplicacion.place( x = 250, y = 90)
division = tk.Button(ventana, text="/", command=Division)
division.place( x = 360, y = 90)
boton_salir = tk.Button(ventana, text="Salir", command=ventana.quit)
boton_salir.place( x = 190, y = 250)
ventana.mainloop()